# Configuração opcional carregada fora do pacote da aplicação.
# Este arquivo sobrescreve o application.properties quando for encontrado.

spring.datasource.url=jdbc:mysql://localhost:3306/dbSmart40?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=America/Sao_Paulo&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=senai

estoque.api.url=http://localhost:8088/estoque
expedicao.api.url=http://localhost:8088/expedicao
server.port=8088
